### ISSUE TITLE
Extension seems to be making Youtube go haywire

### ISSUE THREAD

**Issue by RazaZaidi2802** [0x48piraj/fadblock#125] opened 2023-11-17 06:09 UTC
https://github.com/0x48piraj/fadblock/assets/58148776/8151b274-e715-4e03-b8c6-87aa03e57571

Disabling the extension makes youtube work normally

**Comment by 0x48piraj** [comment] 2023-11-17 07:02
That doesn't seem good, I am looking into it as I received a few reports like this. Does it happen with every video or some, what's the frequency of this bug? Is it reproducible?

Also as one user suggested, 

> I found out that if certain videos were skip, try going to the channel, find the video in "video" section, ( won't work if you click same video shown in "Home" section), click the video you found, and it will not be skipped anymore.

Does the above solve the issue temporarily or does every video get skipped no matter what?

**Comment by RazaZaidi2802** [comment] 2023-11-17 07:17
It was happening to every video I opened but it would randomly stop then suddenly start again on all videos again. As you can see I have multiple tabs open so it either happened on all of them or none of them at random.

I re-enabled the extension to check and you're right, it doesn't happen if I load the video from the channel's page, but if I refresh the page, it starts happening again. Currently going through the "happens to all youtube tabs" phase

https://github.com/0x48piraj/fadblock/assets/58148776/59e7bccf-465f-48e0-aef6-111b7ecf4d01

**Comment by mlqh** [comment] 2023-11-17 09:35
This is the exact issue I meant in [119](https://github.com/0x48piraj/fadblock/issues/119), thanks to Raza for posting a video of it, just wanted to let you know.

**Comment by diego10arg** [comment] 2023-11-17 10:37
At the end of the haywire, if you click on the replay button it will play fine but muted. I have to mute and unmute audio un order to listen. (There is no need to reload the page to play it properly).

Thanks!

**Comment by RazaZaidi2802** [comment] 2023-11-17 11:35
> At the end of the haywire, if you click on the replay button it will play fine but muted. I have to mute and unmute audio un order to listen. (There is no need to reload the page to play it properly).
> 
> Thanks!

Doesn't work for me. Clicking replay makes it go haywire again. And again. And again.

**Comment by lianglee** [comment] 2023-11-17 12:33
Yes i can confirm issue started today

**Comment by diego10arg** [comment] 2023-11-17 12:38
I believe it is not related to the video itself rather than YT logic to show ads.
I have been playing short videos with no issue and suddenly it happend with one from the same channel. After all the haywire I pressed Control+F5 to fully refresh and since the ads "were recently shown" it played without a hitch.

**Comment by KnightGabriel** [comment] 2023-11-17 17:06
I'm having the same issue, however, it's only when I open a youtube video in a new tab or from an external link. Clicking on a video directly from youtube(whether it be from a channel's page, the YT home page, or the "recommended" section on the right of a video I'm watching) causes it to work normally.

**Comment by zaeonNineZero** [comment] 2023-11-17 22:16
> I am not sure but for me, it seems to only happen with videos that don't have an ad at the beginning. Is it possible that the extension sees the video as an ad (since there isn't one) and therefore tries to skip it?

I'm pretty sure that's exactly what's happening. Worse still, each skip attempt on the video adds to the Video Ads blocked counter, rapidly triggering the lifetime license pop-up.

I would not be surprised if this was an intentional countermeasure attempt by Google to interfere with FadBlock and make it unusable or too annoying to use.

**Comment by 0x48piraj** [comment] 2023-11-18 09:14
I have confirmed that the issue is caused by Google changing elements locally via Javascript (DOM manipulation) causing this ruckus.

I'm in a bind, as the issue is not reproducible at my end. YouTube is really getting on my nerves. I want to do a complete refactor but it will take a lot of time, I am working on a quick fix which hopefully will be released after the weekend.

**Comment by 0x48piraj** [comment] 2023-11-18 09:59
The new version has been submitted to the web store. Now we wait for the release. Other than the fix, an "update to latest" button was also added for fetching the latest patches from the in-built backend.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/67d91d78-82d5-4d32-bd3f-730fe11aeaee)

**Comment by mlqh** [comment] 2023-11-18 21:42
Yeah makes sense, thanks for taking the time and effort to look into this, and for making the extension as a whole, really appreciate it!

**Comment by yoniwulf** [comment] 2023-11-19 18:48
Would it be possible to check if x number of seconds/minutes of the actual video have been played while trying to skip an ad. That way if the extension sees that more than x seconds/minutes have passed, it knows that it is skipping the actual video, not just an ad. It could then go back to the beginning of that video and play. Not sure how viable of a fix that is.

**Comment by 0x48piraj** [comment] 2023-11-21 11:00
The new version (v2.6) is out guys, see if it solves the problem or not.

**Comment by diego10arg** [comment] 2023-11-21 12:59
Hi @0x48piraj , so far it seems to be working properly!

Thank you so much for your effort!

**Comment by 0x48piraj** [comment] 2023-11-25 18:07
Closing then.

**Closed by 0x48piraj** 2023-11-25 18:07 UTC
