### ISSUE TITLE
it skip the whole video now

### ISSUE THREAD

**Issue by rain23764** [0x48piraj/fadblock#128] opened 2023-11-17 13:22 UTC
have issue with it skip the whole video, same as reinstall fadblock

**Comment by Atsilut** [comment] 2023-11-17 14:05
Same here, I'm using Chrome on Windows 11 (not recent updated)

**Comment by 20112m** [comment] 2023-11-17 14:22
Same issue for me, it skips the entire video and mutes it.
Using chrome on windows 10

**Comment by PatFat8r14u4** [comment] 2023-11-17 16:20
Same issue for me, it skips the entire video and mutes it.
Using Edge on windows 10

**Comment by harkai84** [comment] 2023-11-17 16:39
I am using Brave Browser on Linux. It works fine for me.

**Comment by BaldissaraMatheus** [comment] 2023-11-17 17:41
It's happening for me too, I'm on Floorp (a firefox fork). Browser version is 11.5.1 (based on firefox 115.4.0) and Fadblock version is 2.5

**Comment by xanat0s** [comment] 2023-11-17 18:23
Same here on Chrome + Windows 10. The extension is incredibly broken at this point. If you continuously click on the video's timeline, you can eventually get it to start playing normally. 

However, in one case last night, it actually skipped the video entirely and started playing the next video in the author's playlist. This happened 4 times in under a second, such that I had to click _back_ multiple times on my browser just to return to the original video I was trying to play. This happened multiple times before the above-mentioned workaround finally got the video to start playing normally. 

> Hello, which browser and os do you use? Maybe a Link to a youtube video.

It has nothing to do with any specific video.

**Comment by mazpeng** [comment] 2023-11-17 22:15
Same issue

**Comment by EthanPany** [comment] 2023-11-17 23:19
Same with Arc (Chromium) + macOS 14.2, it worked at first but never working again in the past few weeks.

**Comment by BaldissaraMatheus** [comment] 2023-11-18 00:54
> It's happening for me too, I'm on Floorp (a firefox fork) under Arch Linux. Browser version is 11.5.1 (based on firefox 115.4.0) and Fadblock version is 2.5

Now it's working fine for me, even though I didn't do anything

**Comment by JustSvenYT** [comment] 2023-11-18 01:24
Same issue with Opera GX on Windows 11.

**Comment by Victorlauni** [comment] 2023-11-18 03:25
Same issue with Firefox (119.0.1) and fadblock 2.5
The bug occurred to me randomly, most videos can play normally, but sometimes it skipped.
While the bug got triggered, the video instantly skipped to the end and flashing with black screen while the replay button switching between "replay" and "play". Seems like the video was skipped and replayed and skipped again in a loop.
If I manually stop it and start the video from beginning, the video can play normally but muted, even though the volume is set to 100%.

**Comment by Victorlauni** [comment] 2023-11-18 03:35
I find a pattern when the bug occurred. If I reload youtube (f5) and click on a video instantly or open youtube video in a new tab, the bug always got triggered.
And if I reload youtube and wait for a few second before clicking the video, the video can play normally. 
The bug may cause by sth from youtube not being loaded correctly in the background I guess.

**Comment by rain23764** [comment] 2023-11-18 04:27
> Hello, which browser and os do you use? Maybe a Link to a youtube video.

i have 2 laptop bith run win 10 and 11 with latest chrome browser
and it happening on other videos too
rn i remove it and hope theres fix later since i really like to use it it actually no give me the annoying message after i install that

**Comment by PatFat8r14u4** [comment] 2023-11-18 05:41
To fix the audio issue. 
Just move the volume bar from bottom to top.
Then sound will come. 

> Same issue with Firefox (119.0.1) and fadblock 2.5 The bug occurred to me randomly, most videos can play normally, but sometimes it skipped. While the bug got triggered, the video instantly skipped to the end and flashing with black screen while the replay button switching between "replay" and "play". Seems like the video was skipped and replayed and skipped again in a loop. If I manually stop it and start the video from beginning, the video can play normally but muted, even though the volume is set to 100%.

**Comment by 0x48piraj** [comment] 2023-11-18 09:20
Guys, here's the original thread (https://github.com/0x48piraj/fadblock/issues/125), let's stick to one thread rather than opening multiple threads with the same issue.

The problem is Google doesn't do patches globally so I am not seeing this happen at all. But from the reports, I think I know what the problem is, I will release a patch quickly nonetheless, which will come out after the weekend unfortunately as web stores are very slow to publish.

**Comment by 0x48piraj** [comment] 2023-11-18 09:58
The new version has been submitted to the web store. Now we wait for the release. Other than the fix, an "update to latest" button was also added for fetching the latest patches from the in-built backend.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/67d91d78-82d5-4d32-bd3f-730fe11aeaee)

**Comment by 0x48piraj** [comment] 2023-11-21 16:56
Please report if the new version works or not so I can close the issue.

**Comment by b940315** [comment] 2023-11-21 17:21
So far, so good. From Taiwan. Thank you!

**Comment by b940315** [comment] 2023-11-21 17:24
<img width="806" alt="image" src="https://github.com/0x48piraj/fadblock/assets/55653865/3ea370ed-d7fa-4c41-be96-9d326e62cf07">
Although there are still some ads that haven't been skipped

**Comment by 0x48piraj** [comment] 2023-11-21 17:24
Thank you, it's almost confirmed that YouTube is messing with FadBlock too so now I will have to know if the project stops working so I can quickly release counterpatches.

**Comment by b940315** [comment] 2023-11-21 17:38
Maybe I forgot to hit F5; still testing.

**Comment by 0x48piraj** [comment] 2023-11-27 23:28
Seems like it's stable now. Closing.

**Closed by 0x48piraj** 2023-11-27 23:28 UTC
