### ISSUE TITLE
Open Core Debate

### ISSUE THREAD

**Issue by Cynosphere** [0x48piraj/fadblock#42] opened 2023-10-31 03:19 UTC
Firefox asked me to accept new permissions and `extensionpay.com` was listed as one of the new domains needing permissions. Care to explain?

**Comment by 0x48piraj** [comment] 2023-10-31 10:04
Care to read "MAJOR ANNOUNCEMENT" on the project homepage with big flashing loudspeaker emotes, if not, reading the "Release notes" over Firefox itself before issuing this big-swanky title?

Closing.

**Comment by Peacock365** [comment] 2023-10-31 14:16
Except your "Major Annoncement" doesn't address the extensionpay.com addition at all. It is also bad practice to put out new versions before having updated the code here, this is generally considered a bad faith move for an open source project.

**Comment by JBYoshi** [comment] 2023-10-31 15:57
I see two separate concerns here: 

> this is generally considered a bad faith move for an open source project

I think the announcement is supposed to explain this as implying "the extension will no longer be open source".

> your "Major Annoncement" doesn't address the extensionpay.com addition at all

This is the part that *wasn't explained* in either the announcement or the Firefox changelog, and what I think mainly needs to be clarified.

**Comment by Cynosphere** [comment] 2023-10-31 16:04
It's not wrong that it isn't in the announcement, it's just way too vauge

> the repository will transition to an *open-core model for ongoing maintenance and updates*

Like I've never heard of the term "open-core model" before this.



Whatever, mutation observer update broke the entire extension for me anyways and I'll just stop recommending it to friends as is because of all of this. Have fun trying to secure funding because you don't want to get a day job and probably worship Louis Rossmann like he's the new RMS in trying to find funding similar to what FUTO is doing with Grayjay.

**Comment by 0x48piraj** [comment] 2023-10-31 21:36
Reopening the issue as it seems people really are getting confused despite the supposedly clear announcement.

**Comment by 0x48piraj** [comment] 2023-10-31 21:58
The open-core model is a common concept in the open-source community, but I overlooked the fact that the majority of **Issue** creators are actually customers, unlike the typical scenario involving fellow developers for most projects.

I'm sorry to hear that @Cynosphere, what's the Firefox version and platform were you using?

I am not going to "secure funding" for a simple application like this, it was created for free but I didn't assume this extension will amass this huge an audience (>400K). By the way, I have no idea about Louis and that reference.

I hope you all understand how much time and energy it takes to maintain something like this where YouTube is actively trying to shut-out everything for such a large userbase while trying to work >80 hours on your own thing. If you are not happy with the decision, you're happy to downgrade the version to 1.3 as I won't take anything down, it just won't be maintained. I think that is fair.

@Peacock365 and @JBYoshi, I understand the fear of seeing an unknown URL access and so, I have added a note explaining why is it there in the extension. I hope you all can understand where I am coming from, but if you don't it's understandable.

**Comment by Peacock365** [comment] 2023-10-31 23:26
@0x48piraj 

Making your extension closed source will immediately make it unattractive to a lot of people. Certainly, I am not inclined to install any closed source software when there are open source alternatives. And rest assured, another blocker doing the same thing as yours will overtake your extension in no time, if you are going down the closed source route. 

I can tell you why you have 400K users now. You ahve 400K users now because YouTube chose to crack down on adblockers worldwide, your solution is innovative and evades the detection uBlock Origin and other extensions have to deal with.

But if you hope to monetize it aggressively, this is doomed to fail. Because, at this point, why shouldn't I pay for YouTube Premium instead, if I have to pay anyway? Not to mention that another extension doing the same thing will overtake your closed source one in no time, did I already mention that? I mean, a donation button in your extension is 100% acceptable, if people want to support your work financially, they should be able to. Locking features behind a paywall, making it closed source... all of that is going in the wrong direction, dear developer. I am just giving you friendly, well-meaning advice here. Seldom have I seen an extension that popped up, instantly became so popular, and went into the wrong direction after like... two weeks? This is not a path I and many others are willing to follow you through. Look at uBlock Origin, and the integrity of its developer team. Again, it's fair to ask for donations, paywalling and making this closed source is not.

**Comment by 0x48piraj** [comment] 2023-11-01 00:02
uBlock Origin has hundreds of people employed whereas I am the sole project maintainer, and a quick Google search shows is a part of the "Acceptable Ads Program" and that can explained with the following example, **[Adblock Plus](https://www.statista.com/statistics/1219216/adblock-plus-eyeo-revenue/) reported 55.8 million euros in revenue back in 2020**. That doesn't seem like "free" to me, does it? Hmm.

Also, the extension is placed at a **measly 5.99$ for a lifetime** with regular updates whereas YouTube Premium costs **$13.99 per month**. I mean I understand if you don't want to pay for something that was once free, it's natural, but don't come up with illogical statements, that's just funny.

**Comment by Peacock365** [comment] 2023-11-01 00:07
@0x48piraj 

Way to miss the point of my post. I am out, but not out of options. The fact that you are demanding money is the least of your issues. Start with the closed source nature of the extension and the lack of transparency recently.

**Comment by 0x48piraj** [comment] 2023-11-01 00:14
Do all the extensions you currently have and every software installed on your Desktop is open-source?

I am being anything but transparent, addressed all your issues, reopened this thread for discussion and feedback. All released versions have detailed release notes as well as the descriptions have been updated.

It's okay to disagree but it's not a channel for you to attack. Open-core is not a new-fangled idea, it's been around for decades, from RedHat to MySQL utilize this model.

**Comment by Revemohl** [comment] 2023-11-01 00:33
All I really have to add to this discussion is that if you charge money for a way to get around such an aggressive block, it's very likely that Youtube will pay more attention to your work and do everything they can to either patch up the holes you used, or straight up do something about it by contacting Github, the addon stores or something on that level. 

I'm very thankful for what you've done with this addon (despite not being able to pay for it, my budget is very tight), but be careful about trying to earn money with it since that's usually the tipping point for many issues. I'm also pretty sure that if you just asked for donations, many people would be more willing to help you out.

**Comment by 0x48piraj** [comment] 2023-11-01 01:48
@Revemohl, I understand your point about the whole flying "under-the-radar" thing. It's just that, YouTube is constantly changing things (you can see the Issues labeled "not working") and I am constantly trying to patch things up on my end.

It's currently priced at 5.99$ as a one-time lifetime license fee, is that still a deal-breaker for you?

**Comment by Shadowized** [comment] 2023-11-01 13:31
It's disappointing to see a developer this wildly out of touch with his users.

**Comment by jackloomen** [comment] 2023-11-01 18:24
Someone will just fork the extension and we will move there, delusional snakes make themselves irrelevant.

**Comment by Jo900** [comment] 2023-11-01 19:12
Not going to spend money over a workaround ff extension, you are totally out, wrong marketing!

**Comment by MiniGrief** [comment] 2023-11-01 22:59
> Someone will just fork the extension and we will move there, delusional snakes make themselves irrelevant.

Honestly, there is kind of no need.

Now I'm not going to give exact directions on what to do, but it just so happens that Javascript uses a JIT compiler. So the entire source code is still there in the extension's XPI file on the addon store.

Have fun with that information everyone.

(Yes of course you want to be rewarded for your work. That's fair enough. But take a page out of Winrar's book. Hell, even out of Adblock Plus' book since you like to quote their profits.)

**Comment by 0x48piraj** [comment] 2023-11-02 00:05
Hello again, @Shadowized! Can you elucidate then?

Delusional snakes would have closed the repository and obfuscated the source over stores so people can't understand what's going on (almost all extensions do this), this thread wouldn't have existed, and more, @jackloomen.

@MiniGrief, exactly, or you know, just use the releases page for installing v1.3.

> Have fun with that information everyone.

I mean, the code is right there with instructions on how to sideload an extension; there's no need to keep it a secret or explain it with a hush-hush tone.

I'm now honestly hoping someone forks this repository and builds a fresh extension, tailored to users like you people who expect a developer to put in loads of effort maintaining an extension, even if it's basic and unexciting, ready to invest in maintaining its compatibility and stability over time.

I am not interested in maintaining this monotonous extension or making it generate consistent money, I'm literally asking a LTV of 5$ for my efforts as a good gesture, if the majority of people are still unhappy, I will put back the previous version, leave it unmaintaned, see it get broken by YouYube and move on. Then, it's up to uBlock if they can win the battle or not, which I hope they do.

**Comment by Jo900** [comment] 2023-11-02 02:13
no point to monetize and push people to pay ltv on what can be only a short temporary space left from ytube checks.
And how ethical can be a google soc guy trying to monetize from spaces left uncovered by the same company you work? 
Don't pay ytube premium, pay Piyush instead... you should be the last one to ask for money. No matter the amount of work behind.

**Comment by stephenhawk8054** [comment] 2023-11-02 05:39
I'm not here for the issue. I'm here since I'm not sure why uBO is mentioned a few times now and I personally hope to be able to clarify the information so others will not misunderstand in the future

> uBlock Origin has hundreds of people employed whereas I am the sole project maintainer, and a quick Google search shows is a part of the "Acceptable Ads Program" and that can explained with the following example, [Adblock Plus](https://www.statista.com/statistics/1219216/adblock-plus-eyeo-revenue/) reported 55.8 million euros in revenue back in 2020. That doesn't seem like "free" to me, does it? Hmm.

- uBO is not a company and is not under any organization, and totally not under Adblock Plus,
- uBO does not hire any employees, all the work is done by the developer and the volunteers in their spare time,
- uBO [is not a part in any `"Acceptable Ads Program"`](https://github.com/gorhill/uBlock/blob/master/MANIFESTO.md) and [does not accept any donations](https://github.com/gorhill/uBlock/wiki/Why-don't-you-accept-donations%3F) nor [other kinds of sponsors/finances](https://github.com/gorhill/uBlock/wiki/Privacy-policy)

Again I don't have any problems with the extension nor with this issue. Developer has their own decisions. I personally just want to prevent further misinformation.

**Comment by 0x48piraj** [comment] 2023-11-02 06:59
Sorry I mixed up uBlock and uBlock Origin.

> In July 2018, ublock.org was acquired by [AdBlock](https://en.wikipedia.org/wiki/AdBlock),[[20]](https://en.wikipedia.org/wiki/UBlock_Origin#cite_note-20) and since February 2019, uBlock began allowing users to participate in "[Acceptable Ads](https://en.wikipedia.org/wiki/Adblock_Plus#%22Acceptable_ads%22)",[[21]](https://en.wikipedia.org/wiki/UBlock_Origin#cite_note-21)[[22]](https://en.wikipedia.org/wiki/UBlock_Origin#cite_note-22) a program run by [Adblock Plus](https://en.wikipedia.org/wiki/Adblock_Plus) that allows some ads which are deemed "acceptable", and for which the larger publishers pay a fee.[[23]](https://en.wikipedia.org/wiki/UBlock_Origin#cite_note-23)

**Comment by kdb424** [comment] 2023-11-02 07:10
As someone who has contributed to open source, and maintained a repo with growing popularity, I support your desire to be compensated for your work. If someone wants to build one for free with their own time, good for them. I came here looking for instructions on how to pay for it as even if I got absolutely nothing, and you disappeared tomorrow, I would have felt I get my money's worth. Don't let people get to you. Open source is a lot of work and time that most people don't understand until they have done it. Looking forward to reading the proper place to send the money to get back to watching ad-free. Best of luck to ya!

**Comment by 0x48piraj** [comment] 2023-11-02 07:33
Thank you very much for understanding.

As for the payment, when you go to the FadBlock's UI, isn't there a screen something like this?

<p align="center">
<img src="https://github.com/0x48piraj/fadblock/assets/5800726/4e43f99b-5fec-4bfd-9eb7-b0eaeda6a29d"/>
</p>

I have contributed to open-source projects since I was 17 years old. I am not here for get-rich-quick schemes. I will try my best to keep the extension running as long as possible. If someone buys it just before it stops working, I will be happy to issue a refund as well. I have open-sourced a lot of quality projects but maintaining an active project is not an easy job. It consumes a lot of time and effort and that's okay but when you're trying to work on your own business along with contractual work and side gigs, it becomes exponentially harder.

> Note: I am testing a lot of things after getting backlash here as well in reviews, about what the community wants, is the price point justified, is the hard paywall a good choice, or whether it should run even after the trial ends but asks for the license sometimes rather than on each video, the performance and compatibility issues, and most of all, **should I even bother maintaining and improving this or it's a lost cause**. So, I'm very grateful for those kind words.

**Comment by kdb424** [comment] 2023-11-02 07:53
I'm not seeing the screen, but will check after an update. If you want the best results with users doing as they have been, it may be worth more to not lock it down, keep it open, and just putting the time in based on how much you get from donations, or your own personal desires. I understand very much that when a project gets way more attention than expected that it can be overwhelming, and can make you feel pressured to do more or different work than you may have done if it had a small following. Don't let the numbers change what you want to do and just ask for donations where possible. Those of us that are willing to donate would be happy to do without a paywall. Just need an easy access button to do so!

**Comment by Driftlife** [comment] 2023-11-02 08:01
I don't understand. If you want to pay, just pay. If you don't want to pay, just use free open source software. Because some software is open source and free software, it is required that every software should be open source and free software. This is a very strange thing.

**Comment by 0x48piraj** [comment] 2023-11-02 08:15
@kdb424 which browser are you using? If it's Firefox, the version is 1.6, but if you're a Chromium-based user, I haven't released the changes because I wanted to avoid disrupting the extensive user base and creating chaos before resolving and fixing all the issues.

@Driftlife exactly, the repository is here and will be here, developers are free to fork and create a better version, and distribute it for free as well and people who want to use the previous version (1.3), can just download it via the Releases page (which still works for most people because YouTube is releasing geo-based patches).

But for some it's not working because of those new patches, for some, it slows down the YouTube interface a bit (as the codebase is pretty rudimentary), for some, it doesn't work because of compatibility issues and, at last, a few people are not carefully reading the FAQ and switching off other adblockers.

I want to help everyone, I do, but I really don't have the time to do this kind of extensive free work :(

**Comment by kdb424** [comment] 2023-11-02 08:19
I'm on Firefox. I may not have hit the limit yet. I'm sure I'll trigger it at some point. Will check in the morning.

**Comment by 0x48piraj** [comment] 2023-11-02 08:29
Again, thank you for the advice.

> not lock it down, keep it open, and just putting the time in based on how much you get from donations, or your own personal desires

I probably will remove the total lock-in (I went ahead with it simply because the implementation was relatively straightforward), making it so that people can use it infinitely as well as learning to allocate my time based on license purchases and donations.

**Comment by MiniGrief** [comment] 2023-11-02 14:12
> I don't understand why people can't provide constructive criticism like you instead of jumping to the conclusion that all developers are trying to deceive or manipulate. I was close to the point of leaving the extension in its current state and discontinuing maintenance altogether.

Look, I think there's just been a misunderstanding with what people are angry about. Part of what makes open source software great is what you suggested people do, fork it and make it their own. Usually what happens when a repo maintainer has no motivation to work on a project is... nothing. They just stop. Someone else will come along and fork it to continue it. It's kind of the way things have happened forever and it's what's considered the norm.

I personally am not trying to downplay the work you put in. I've maintained open source software in the past and yeah, it's a hell of a lot of work. But I've never went and forced people to pay for anything I've made as it's generally considered 'what the bad guys do'. Turning an open source project into a closed source one which has a price tag is heavily frowned upon here.

If you genuinely believe you need a paywall of sorts, please consider just paywalling some extra features and leaving the base functionality alone.

**Comment by Peacock365** [comment] 2023-11-02 18:02
@0x48piraj 

Thank you for doing the right thing with version 2.0. Now that the extension is no longer paid and relies on donations, is there a good reason to keep it closed source? I think it would have a higher appeal if it was open source again.

**Comment by 0x48piraj** [comment] 2023-11-03 00:30
@MiniGrief, I understand your point, but the constant need for updates (the new version is breaking for many people as YouTube again put out a new patch) compelled me to work on this a lot more than I originally wanted to. For updates and maintenance, this is a common model, the base functionality is static, and I don't think it needs any features, one I recently thought of was to check installed extensions within and notify if any other adblocker is found present, but it's not a good choice to overcomplicate the extension.

@Peacock365, the source remains closed due to the need for continuous updates, and insufficient time to maintain without much support not to mention the codebase now contains a payment processing mechanism.

**Comment by Driftlife** [comment] 2023-11-03 01:42
It is required to be open source but no one helps to maintain it. There are more and more problems, but it can only be free. When I provide DOM state for authors to maintain, the price of 6.99 becomes a pittance. 200,000 Google users but only one maintainer

**Comment by DeceptivePastry** [comment] 2023-11-06 04:13
You seem frustrated by the response you got to trying to monetize but I think you mainly went about it the wrong way. People using a free extension just out of the blue see an error message and request to allow something called "extensionpay", people are naturally going to be suspicious and resistant even if it is worth the price. Especially considering the whole point of using this particular extension is to avoid paying someone money. Would've had a better response just having a one time or rare popup asking for donations imo, or forking to a "pro" version with extra functionality. I mean, I do appreciate the extension and the work put into it.

**Comment by 0x48piraj** [comment] 2023-11-06 11:54
I am beginning to understand the exact same thing. It's just that when people start saying things like,

It's not a good feeling.

The only reason to implement the popup was to justify the time investment. I am constantly working on various side gigs and this was a small tool which when building I was like "huh, good idea let's do it", I didn't think how much of a time-suck it would become to fix compatibility issues (Firefox, Chrome, Brave, Opera, Edge...Vivaldi?) and providing support for such a huge userbase.

I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.

I am happy to lower the amount as well (I gave lifetime licenses to people who donated 1$ as well). I am happy to refund too if it stops working on the day you bought it or something. But people personally attacking me instead of requesting changes just...

I hope it works for a while this YouTube drama stabilizes and everyone can go back to using uBlock Origin.

**Comment by iaxivers** [comment] 2023-11-06 16:15
> 
> I am happy to lower the amount as well (I gave lifetime licenses to people who donated 1$ as well). I am happy to refund too if it stops working on the day you bought it or something. But people personally attacking me instead of requesting changes just...

You shouldn't have any sort of payment fee, trust me, you'll be highly respectable if you go down the donation route, and you'll probably make a lot more money, look at winrar f.ex

**Comment by Jo900** [comment] 2023-11-06 21:23
> @DeceptivePastry, I am beginning to understand the exact same thing. It's just that when people start saying things like,
> 
> "Rubbish. Didn't work that well before and now he's asking for money? He'll probably take it and bounce. Wouldn't give him a cent."
> 
> "Don't give scammers your hard earned money."
> 
> "I am not gonna pay u for this extension lmao. If I'm gonna pay someone to not see ads I would rather buy the Youtube built in ad blocker: YOUTUBE PREMIUM!!!"
> 
> "Aside from having to reload pages over and over cause this addon is scuffed af, this absolute garbade addon will lock u out of youtube after "skipping" 56 ads and u'll get a popup to pay the scummy developer. Shame"
> 
> It's not a good feeling.
> 
> The only reason to implement the popup was to justify the time investment. I am constantly working on various side gigs and this was a small tool which when building I was like "huh, good idea let's do it", I didn't think how much of a time-suck it would become to fix compatibility issues (Firefox, Chrome, Brave, Opera, Edge...Vivaldi?) and providing support for such a huge userbase.
> 
> I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.
> 
> I am happy to lower the amount as well (I gave lifetime licenses to people who donated 1$ as well). I am happy to refund too if it stops working on the day you bought it or something. But people personally attacking me instead of requesting changes just...
> 
> I hope it works for a while this YouTube drama stabilizes and everyone can go back to using uBlock Origin.

You speak as you are the only one working on time consuming projects. 
About asking money usually is needed to understand how people think more than what you think to deserve. 

 I'll tell you my point of view (free of charge of course), usually people are going to spend money for services or for somenthig they feel as un-replaceable. 

Your browser extension is not a service and is not un-replaceable, is just a smart workaround, and as soon ytube update their checks will be useless. So stop enjoying your fame moment on big tech company fail (and as i read you also work for them making you ethically weak) and start thinking you are helping a community of people harassed by ytube invasive ads.

In this case the only way is donation, as the money are given by graditude. The exact moment you force that gratitude process, people will give you a buck of f0cks instead. You must be young guy, learn the world same time as the code.

**Comment by Arcelibs** [comment] 2023-11-07 07:00
> > I am beginning to understand the exact same thing. It's just that when people start saying things like,
> > "Rubbish. Didn't work that well before and now he's asking for money? He'll probably take it and bounce. Wouldn't give him a cent."
> > "Don't give scammers your hard earned money."
> > "I am not gonna pay u for this extension lmao. If I'm gonna pay someone to not see ads I would rather buy the Youtube built in ad blocker: YOUTUBE PREMIUM!!!"
> > "Aside from having to reload pages over and over cause this addon is scuffed af, this absolute garbade addon will lock u out of youtube after "skipping" 56 ads and u'll get a popup to pay the scummy developer. Shame"
> > It's not a good feeling.
> > The only reason to implement the popup was to justify the time investment. I am constantly working on various side gigs and this was a small tool which when building I was like "huh, good idea let's do it", I didn't think how much of a time-suck it would become to fix compatibility issues (Firefox, Chrome, Brave, Opera, Edge...Vivaldi?) and providing support for such a huge userbase.
> > I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.
> > I am happy to lower the amount as well (I gave lifetime licenses to people who donated 1$ as well). I am happy to refund too if it stops working on the day you bought it or something. But people personally attacking me instead of requesting changes just...
> > I hope it works for a while this YouTube drama stabilizes and everyone can go back to using uBlock Origin.
> 
> You speak as you are the only one working on time consuming projects. About asking money usually is needed to understand how people think more than what you think to deserve.
> 
> I'll tell you my point of view (free of charge of course), usually people are going to spend money for services or for somenthig they feel as un-replaceable.
> 
> Your browser extension is not a service and is not un-replaceable, is just a smart workaround, and as soon ytube update their checks will be useless. So stop enjoying your fame moment on big tech company fail (and as i read you also work for them making you ethically weak) and start thinking you are helping a community of people harassed by ytube invasive ads.
> 
> In this case the only way is donation, as the money are given by graditude. The exact moment you force that gratitude process, people will give you a buck of f0cks instead. You must be young guy, learn the world same time as the code.

I'm pretty sure you're making a joke. Sorry, but I've never seen anyone willingly donate.
As for alternatives, I'm quite certain people would rather use a VPN to pay YouTube in Turkey.

Let me tell you from a practical standpoint, people just love free things. It all goes wrong from the moment they perceive YouTube as a free platform.

So, my advice to the author is to slow down all updates and take more rest. After all, no one will thank you or pay you for it.

**Comment by ArcboundX** [comment] 2023-11-07 08:48
I don't think this is the way to go about it.

I'm not paying for YT Premium because i don't have money, i'm not paying for YT Premium because i'm not going to be paywalled out of using YT under the threat of not being able to use the platform if i don't do what they want, or buy what they sell.

And the same goes for Fadblock, it's useful and practical, but i'm not going to want to use it if i have to pay for it under the prospect of it becoming unusable, or being spammed with messages ad-nauseam. 

My suggestion is that if you implement a voluntary donation system instead you won't see goodwill dry, until then i'll take my chances with Ublock Origin.

**Comment by Profeces** [comment] 2023-11-07 20:49
I appreciate the effort you made in creating this extension. However, the decision to force a license in the manner you did is sketchy at best. Reading your reactions to people being concerend a bout this, is a complete deal breaker. 

The sheer amount of entitlement in every one of your messages is actually disgusting. Your justifications and claims that "it's not about the money" and "this isn't a money grab" is not only complete BS, but insulting to the intelligence of anyone with the most basic ability to follow even the simplest of logical duductions. 

You also have no integrity at all since you've mentioned you actually work there. So you knew exactly when this was coming, and just so happened to have this extension available immediately, when all others weren't working. You obviously used your knowledge on the job to prepare for this to happen. It was released, and advertised, as a "fast and friendly" solution to youtube ads. Then, you paywall it in a way that is damn near ransomware in nature. This is so morally and ethically unacceptable that I almost don't even have words to describe it.

You then have the audacity to downplay the fee for the license, claim it's not about money, while in the same breath boasting about how more than 400k people are using it. If even half of the users pay this random fee then you net a cool mil. Yeah, not about the money at all, right? If you can do simple math, you fully understand why this "low fee" was added. 

It's all about the money. As other users have pointed out, this is something that will 100% be patched out anyway. The only reason you made that decision was for a literal cash grab, and if you think for a second that anyone doesn't see through you, you're mistaken. 

The kicker is, I would have gladly donated to this project. Someone said above that no one willingly donates, but that isn't true. The entire content creator space exists solely based off of donations. (You know the platform that this extension is actually for?) 

People can, and will, donate to a project that they can get behind. I'm one of those people who would have. I wasn't asked, though. I saw a screen that basically tried to force my hand into it. That's not the way. I did not use open source software to get hit with a demand for funding a week later. 

Again, I do appreciate your efforts in making this. I do like the project. But, I don't like you. How you've represented yourself in this thread is all the proof that I need, that I do not want to be any part of any project of yours. I'd have gladly supported the product, but it's you that I will never support. Your attitude and lack of any sort of ethics at all in the opensource space is revolting.

**Comment by 0x48piraj** [comment] 2023-11-08 08:35
Oh man, where should I start...

Let's start with @iaxivers and @ArcboundX  as they were the only ones to provide constructive criticism, it's an optional popup, not a paywall, and I understand that it's frequency is quite high at the moment (I didn't know that people in the States are getting >4 ads per video, that's insane) and has been tweaked and submitted to the store which will go live soon. The extension was also tweaked in a way that it doesn't need reloads after the limit is hit, it works regardless which improves the user experience. I am sorry for all the inconvenience. Hope you can hold out till the new version drops (disable it for a while if it's too annoying).

As per @Jo900 whom I am trying hard to ignore but he's been at it down-thumbing every and all comment which doesn't soothe his opinions, which is okay but now people like @Profeces are also getting in the mix so I have to clear the air.

I DO NOT WORK AT GOOGLE. PLEASE. SEARCH UP THINGS BEFORE BLATANTLY ASSUMING. I was an open-source contributor at [OWASP Foundation](https://owasp.org/) under Google Summer of Code Program. It's not a job. Barely an internship.

Ergo, I don't have any sort of "secret" from Google.

You don't even understand how this works before uttering the words "it will be patched anyways", like read a bit about how websites work, won't ya?

And please, don't ever talk about open-source, I have been in this space for more than 7 years now. I bet you didn't even read the announcement and googled "open-core model" or even read the comments above. I am disgusted by people like you who only know how to abuse open-source work and mindlessly berate the developers for asking for a donation.

Now, I want to insult your intelligence because you couldn't even "deduce" that and more but I won't. Nor will I counter your oh "400K x 5.99 = million wow!" logic because clearly, you don't have any business background and don't understand anything about conversion rates. And, most of all, why do you care? Are you worried I may earn a "million" from this?

At last, I am showing you the popup for god's sake, not tying your hands, just click cancel and go on, furthermore, I am increasing the frequency as well, and all this after serving for more than a month for free, if you are this intelligent, why don't you fork this STILL open-source repository, build an extension, and serve the community yourself, maybe then you'll realize what I am talking about.

**Comment by Jo900** [comment] 2023-11-08 10:51
This your last comment qualify you and show to everyone all the truth and your real attitude, there is nothing more to add, 40comments you still not get the point. 
Plus you are thinking to mute everyone except who please you. Or better delete the whole thread...  

And yes, is a cash grab. 

I surrender here. Peace!!

**Comment by 0x48piraj** [comment] 2023-11-08 13:38
You should be a politician, you very well know how to twist statements out of context.

Anyone who is a 'human' and has feelings will be frustrated by these remarks, and I am not going to behave like a NPC developer copy-pasting a nice reply to come across as a "good guy". You are free to assume that I am rude or arrogant or any number of things but I won't tolerate baseless comments.

I changed the frequency the moment I saw the first 2-3 comments and uploaded the new version. The Chrome dev team has a detailed review process and takes at least two days to process new updates. All I can do is to tell people to wait till the update drops.

I am going to push some performance optimizations on the next update and will be adjusting the frequency if it's still not adequate after surveying the users.

Generally, if a service is replaceable, less than 1% of users opt to pay for additional features, while FadBlock is based on entirely voluntary contribution. The current conversion rate stands well below 0.1%, but it still provides adequate support to sustain the project. Again, if it was a cash grab, it wouldn't be voluntary as well as I wouldn't have adjusted the popup immediately.

**Comment by Profeces** [comment] 2023-11-11 01:05
> And please, don't ever talk about open-source, I have been in this space for more than 7 years now. 

Congratulations. I, on the other hand, have been in the OSS space since the late 90's (which based on your attitude, I'm pretty sure predates your actual existence) both as a supporter and contributor. I made this account specifically to reply to this, because I don't want my actual account in any way associated with a shady dev like you. You have no clue the projects I've contributed to, or my experience with anything. This, again, just shows how out of touch you are with your userbase. Instead of listening to everyone telling you that you went about this the complete wrong way, you just triple down on it. There's a reason there's multiple reddit threads and all the comments here. When you find yourself in a position where everyone is saying you're wrong, you aren't right buddy. 

>I bet you didn't even read the announcement and googled "open-core model" or even read the comments above. I am disgusted by people like you who only know how to abuse open-source work and mindlessly berate the developers for asking for a donation.

You didn't ask for a donation. You silently pushed an update without even updating the code, which if you actually knew anything about OSS, you'd know is a huge red flag for a dev. Also, since you clearly are so dedicated to being right, that you apparently lost your ability to read; I even said I'd donate to this project. If it was presented in a different way, and you didn't implement the license in the way that you did, I would have done so gladly, just like I have supported countless other projects. 

You're talking to someone who regularly supports OSS projects and telling you why I won't be supporting yours. Instead of taking anything out of that, and possibly learning why you're getting the reaction you are, you instead just want to say you're right and everyone else is wrong. 

>At last, I am showing you the popup for god's sake, not tying your hands, just click cancel and go on

Yeah, click cancel on every single video, sometimes multiple times in a video. At that point it's the same thing as just clicking the skip ads button. Your addon turned into the very thing that it was designed to prevent. Unless, of course, you pay up. 

>furthermore, I am increasing the frequency as well, and all this after serving for more than a month for free

Oh, boo hoo! Cry me a river. I've worked on very large projects, donating my time for free for years before seeing a dime for my efforts. That's my entire point, though. You just wanted to make a quick buck based on the demand for a project like this. You keep saying it's not about money, yet you continue to cry about the amount of effort you spend without making money. That's part of the process. 

> if you are this intelligent, why don't you fork this STILL open-source repository, build an extension, and serve the community yourself, maybe then you'll realize what I am talking about.

I fully understand what you're talking about. I know full well what it is like to contribute to projects for free for extended periods of time. I wouldn't fork this because I know the hassel it would become. I'm not debating that it's a lot. Hell, a small project with a few thousand end-users can be a lot too, let alone one that blew up this fast. Did you see me say even once that the price you were wanting was too high? Did I ever once suggest how much this project would be worth to an end-user? Nope. I sure didn't.  It's not a matter of wanting donations, or money for your time. It's the very shady way you went about it. 

My entire point is that had you went about this differently, the response would have been different. You pushed the update in a shady way, and the impact it had on your end-users was a disaster. Instead of even apologizing or taking any accountability for it whatsoever you just reply with sob stories about the time investment, calling everyone else wrong, and insulting people who disagree with you. 

You need to get your ego out of the way, and listen to the feedback from your users without resorting to your sob stories or know-it-all remarks because you've done this a "whopping" 7 years. No respectable dev conducts themselves in the way that you are, and you should read over this and be ashamed to how you have interacted. The reality is, your project blew up in a way that most devs would beg for. Instead of slowly monetizing it, or fishing for donations the right way, you went too hard and your users let you know. Then they get mistreated and berated by you in return. 

>Edit: If this was a cash grab and I was so unethical, I would have deleted every bad comment or hell, deleted the whole thread, muted specific people, and only kept the "good" ones to coerce more people into donating. Did I?

You and I both know that's not possible. Sure, you could physically do those things, but you can't in practice since this very thread has been linked from numerous outside sources where you do not have that control. (On this note, myself and countless other Devs have repeatedly suggested that it shouldn't be possible at all, because it allows for such an unethical practice.) It would only make things even worse for you if you deleted it. That's all besides the point though. This entire thread wouldn't exist had you done things differently. That's the point you continue to miss, and try to find excuses for at every turn. 

Work on your ethics, don't push code to end-users that hasn't been published, If you're going to accept donations accept them, don't force them. If you're going to force a license to a project, give some sort of notice so your users aren't just smacked across the face with it. These are all very basic principals that you failed at. You need to own it, apologize, and move on. Instead of doing any of those things, you consistently react in an entitled and whiny way, which lead to my initial response to you.

**Comment by 0x48piraj** [comment] 2023-11-21 12:31
Sorry man, I just don't believe you.

> You have no clue the projects I've contributed to, or my experience with anything. You have no clue the projects I've contributed to, or my experience with anything. This, again, just shows how out of touch you are with your userbase.

I am not here to guess what you have done in the past, or how great you are _(I don't know why such an accomplished person will regurgitate their _invisible_ achievements twice)_, **I just care what you say to me and if that makes sense or not.**

> Instead of listening to everyone telling you that you went about this the complete wrong way

How can you say this on behalf of the whole user-base? Do you even know how many personal emails I have gotten, i.e. what's the percentage of people who are "happy", "okay" and "not happy" about the new direction? No, you have no idea, and still, you say in a tone like you know the whole user-base and what they want (you don't).

> When you find yourself in a position where everyone is saying you're wrong, you aren't right buddy.

Here's one, which was like, yesterday (and he was having a problem with login when he reached out):

![image](https://github.com/0x48piraj/fadblock/assets/5800726/7e5bb514-1db0-4810-a5bb-19543a5b5e5f)

WHO IS "EVERYONE". I really want to know.

> You silently pushed an update without even updating the code, which if you actually knew anything about OSS, you'd know is a huge red flag for a dev.

Again, how are you making such bold claims? The first thing was the addition of the announcement, see [here](https://github.com/0x48piraj/fadblock/commit/2cd12ea7d38e3926ed5a47514a333ee084bb5eea).

> Oh, boo hoo! Cry me a river. I've worked on very large projects, donating my time for free for years before seeing a dime for my efforts.

Some people are happy just to be a part of something bigger, I have done that, I have contributed to NASA's OSS Rover Project, Microsoft, Google, and plenty of open-source security projects, I have found high-severity bugs and disclosed them responsibly without any bounty. Why are we comparing now? I don't have time to contribute without any monetary support anymore, it's as simple as that. And if I wanted to make a "quick buck", I would have put up a paywall because of the conversion rates.

> It's the very shady way you went about it.

What's shady in the way I went? Projects that blow up often turn to open-core, that's normal. I don't understand.

> Instead of even apologizing or taking any accountability for it whatsoever you just reply with sob stories about the time investment, calling everyone else wrong, and insulting people who disagree with you.

Dude. Have you looked at all the reviews, issues, forums, and over Reddit? And, do you know about how I emailed every person who donated, personally apologizing when the update broke, reassuring them about refunding the whole amount if I am unable to get it up and working again?

Why do you chalk up things so fast after seeing just one reply? You think a developer will be polite to a person who is shitting on the software, attacking me personally WHILE being completely wrong about what he/she is even talking about? Yes, I am not mature enough to see the other way and still act decently and try to help them, I agree, but, they didn't need to use profanity before even getting ignored or looked over.

> Then they get mistreated and berated by you in return.

Again... They aren't. I am happy that this project blew up and I am grateful, but it's not a software I am proud of, to be honest. It's such a simplistic software which... just piggybacks it's existence of YouTube. It's not something to be proud of.

> These are all very basic principals that you failed at. You need to own it, apologize, and move on.

As I have said above, I didn't push any code without any prior notice, I did not force the donations, it was the best trade-off to harmonize the interests of both parties. I re-adjusted the frequency after listening to the community. I'm just countering false accusations, as I did previously, addressing some of the points that were raised. I do not think that's "whiny" and I am definitely not "crying" about anything, it becomes tedious to invest substantial effort into a project that lacks real-life significance, especially during a phase of life where I cannot dedicate more than 50 hours per week without compensation.

**Closed** 2024-01-25 09:26 UTC
Labels: discussion
