### ISSUE TITLE
Ads are still running

### ISSUE THREAD

**Issue by Chrispybacon1** [0x48piraj/fadblock#29] opened 2023-10-27 15:43 UTC
**Describe the bug**
The Ads are still running, but the screen is blacked out. Audio for the ads is still playing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge

**Comment by 0x48piraj** [comment] 2023-10-27 23:43
Black screen is not an issue which emerges from FadBlock. You have other adblockers running in the background.

**Comment by Chrispybacon1** [comment] 2023-10-28 00:29
I'm afraid that I don't have any adblockers running in the background. I ended up uninstalling all of them. The only other extension I have running is Return Youtube Dislike, but I doubt that's interfering.

**Comment by 0x48piraj** [comment] 2023-10-28 17:52
Yeah Return YT Dislike works well with FadBlock but the underlying issue is definitely caused by other adblockers or if you're on either Firefox or Brave browser.

**Comment by Chrispybacon1** [comment] 2023-10-29 00:16
Strange. I'm on edge, and not using any other adblockers.

**Comment by 0x48piraj** [comment] 2023-11-03 01:07
Probably switch the browser and try again. Addressed. Closing.

**Closed by 0x48piraj** 2023-11-03 01:07 UTC
Labels: bug
