### ISSUE TITLE
Open video in new Tab cause no video but black screen

### ISSUE THREAD

**Issue by itrs** [0x48piraj/fadblock#37] opened 2023-10-29 05:21 UTC
Platform: Firefox / Linux.

Reproduce: open a new video with new tab will cause it no loading but black screen on the new tab
Reload the new tab doesn't help.

(click on video directly without opening it in new tab works fine)

**Comment by JustSimplyKyle** [comment] 2023-10-29 13:26
Can repro, but if you wait long enough(like 30 seconds or something), it will still launch the video

**Comment by kylelau1118** [comment] 2023-10-30 01:47
Same here, can reproduce it opening videos in new tab

**Comment by 0x48piraj** [comment] 2023-10-30 03:10
The black screen is not an underlying issue of FadBlock.

Firefox users: https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop

Brave users: https://brave.com/en-in/learn/turn-off-ad-blockers/

**Comment by JustSimplyKyle** [comment] 2023-10-30 03:15
I'm using edge, which to my knowledge has no kuilt-in blockers

**Comment by 0x48piraj** [comment] 2023-10-30 03:18
Go to `edge://extensions` and see if you have any adblocker installed.

**Comment by kylelau1118** [comment] 2023-10-30 03:31
@0x48piraj didn't quite help, since I have FAQ's ad blocker removed and Brave's shield turned off as well

**Comment by kylelau1118** [comment] 2023-10-30 03:32
> The black screen is not an underlying issue of FadBlock.
> 
> **Firefox users:** https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop **Brave users:** https://brave.com/en-in/learn/turn-off-ad-blockers/
> 
> You have to turn off in-built adblockers. They are getting detected not FadBlock. Please read the FAQ.

@0x48piraj didn't quite help, since I have FAQ's ad blocker removed and Brave's shield turned off as well

**Comment by lockcole** [comment] 2023-10-30 03:44
I have the same problem on Firefox (windows 11) when I open the url directly from address bar. 
It stuck at the following screen for more than 2 minutes before page finish loading.
Interestingly, I tried to disable fadblock and the problem still persist. (I also tried disabling other extensions but no help)
So I think it is not fadblock's problem.

![image](https://github.com/0x48piraj/fadblock/assets/3402682/2779219a-d88e-4176-ba48-7b55e869d6ab)

**Comment by 0x48piraj** [comment] 2023-10-30 04:36
Can I have a list of your extensions @lockcole and @kylelau1118?

**Comment by lockcole** [comment] 2023-10-30 05:49
I have some findings about the problem.
I have tried to clear cookie and data for youtube.com and thus the login session is cleared.
After that the direct link loads immediately without the long waiting time.
However, the problem appeared again when I logged in with the same account.

I tried to switch to other google account and the problem disappeared. It appeared again when I switch back to the main account.


Anyway, I have the following extensions enabled:

AdBlocker Ultimate
Cambridge Dictionary
Facebook Container
FadBlock
Gesturefy
Holodex Plus
Proxy SwitchyOmega

**Comment by kylelau1118** [comment] 2023-10-30 08:43
> Can I have a list of your extensions @lockcole and @kylelau1118?

Not sure what causes the issue, here is a list of the extensions

- Allow Right-Click
- Awesome ChatGPT Screenshot & Screen Recorder
- Clear Cache
- Download All Images
- Easy Auto Refresh
- Export Tabs
- FadBlock
- Google Art & Culture
- Google Docs Offline
- Google Translate
- IG Downloader
- IMDB Ratings for Netflix
- Keplr
- Metamask
- Netflix AutoSkip
- Notion Empty Trash
- Phantom
- Station Wallet
- Tab Suspender
- TraitSniper
- Trim
- Urban VPN Proxy
- Video Downloader for Vimeo
- Wikipedia Reading Lists

thanks for helping out, Raj :)

**Comment by 0x48piraj** [comment] 2023-10-30 09:45
@lockcole "AdBlocker Ultimate" is an adblocker, ain't it? It's in the FAQs as well. You gotta disable them or whitelist youtube.com if you don't want YouTube to detect Adblocker Ultimate and block you.

**Comment by lockcole** [comment] 2023-10-31 02:19
> @lockcole "AdBlocker Ultimate" is an adblocker, ain't it? It's in the FAQs as well. You gotta disable them or whitelist youtube.com if you don't want YouTube to detect Adblocker Ultimate and block you.

Yes, I know that and have whitelisted youtube.com in this extension. And I have also tried disabling it.

**Comment by itrs** [comment] 2023-10-31 03:20
It seems fixed now in v1.5 (Firefox/Linux).

**Comment by 0x48piraj** [comment] 2023-11-03 01:33
Firefox is having quite a few performance as well as compatibility issues :/

I am trying desperately to fix the issue but locally, the new v2.0 works as intended.

**Comment by lockcole** [comment] 2023-11-03 06:57
Thanks for the update.

It seems the "stuck at loading" problem has been fixed on v1.5/1.6 and the adblocking worked well on Firefox.

But strangely after updating to v2.0, the adblocking stopped working even if I disable all other extensions except:
Facebook Container
FadBlock
Proxy SwitchyOmega

**Comment by 0x48piraj** [comment] 2023-11-08 19:15
The issue has been stale for a long time (and hopefully has been resolved, if not feel free to open a fresh issue), closing.

**Closed by 0x48piraj** 2023-11-08 19:15 UTC
