### ISSUE TITLE
Ads are shown and not skipped.

### ISSUE THREAD

**Issue by AlexG2490** [0x48piraj/fadblock#103] opened 2023-11-11 02:21 UTC
Beginning today, November 10th, ads are showing up and playing in full. The addon does not skip them.
Here is the log file you have been requesting from other users.
[LogDump.txt](https://github.com/0x48piraj/fadblock/files/13324142/LogDump.txt)

**FAQ**

1. Are you using other ad blockers?
**No**. I had UBlock Origin which I had stopped using on YouTube. I have now removed it entirely.
![image](https://github.com/0x48piraj/fadblock/assets/60888519/904f0b5d-3ce5-4c29-9c18-ccb9e3966cca)
2. Is your Account blocked?
**No**. YouTube has not given me the "3-strikes" warning or stopped working. The same behavior is present 
![image](https://github.com/0x48piraj/fadblock/assets/60888519/b570634d-110b-4a9c-a598-7087416b7f70)
3. Are you using the Supported version?
**Yes**. I paid the $5.99 two days ago through the integrated menu in the app.
4. Other troubleshooting steps?
I removed the app and added it back again. It now shows that it has blocked 0 ads.
![image](https://github.com/0x48piraj/fadblock/assets/60888519/c303eecd-8dc8-4047-b524-2f12038c52c9)
5. Browser Information?
Google Chrome. Version 119.0.6045.124 (Official Build) (64-bit)

**Comment by LearnToCode2708** [comment] 2023-11-11 02:38
I'm having the same issue now

**Comment by tara2556** [comment] 2023-11-11 03:16
Right. I'm having the same. Maybe youtube update new version

**Comment by 0x48piraj** [comment] 2023-11-11 03:16
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

Note: If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

See here, https://github.com/0x48piraj/fadblock/issues/88, https://github.com/0x48piraj/fadblock/issues/89, https://github.com/0x48piraj/fadblock/issues/87

**Comment by 0x48piraj** [comment] 2023-11-11 03:19
But today more reports have come in, so I will try to reproduce this issue again and let you know if FadBlock has been patched in geo-specific zones or uBlock is still the culprit.

**Comment by openspork** [comment] 2023-11-11 06:09
Same issue here, other adblockers are disabled on YouTube.

**Comment by 0x48piraj** [comment] 2023-11-11 06:17
Can you try incognito mode and see if that works? (enable FadBlock to work on incognito, clear the cache as well)

I am working on setting up a server which will fetch the new patches and easily deploy instantly rather than waiting for the new version update (Google is very very slow at releasing).

**Comment by openspork** [comment] 2023-11-11 06:28
Hmm can confirm it works in incognito, I need a minute to clear cache and test in regular mode but will update.  Thanks for prompt response.

**Comment by CrisWaller1** [comment] 2023-11-11 07:13
I am having the same issue. UBlock Origin is not active on YouTube. I have not been banned from my account. I also have never seen the popup to donate to you (which I would love to do!)

**Comment by 0x48piraj** [comment] 2023-11-11 07:14
@CrisWaller1, you probably installed the extension recently but it's not working, is that the case?

**Comment by CrisWaller1** [comment] 2023-11-11 07:17
I installed it a couple of weeks ago. It stopped working after the last update until I re-enabled it (after contacting you) and was working fine until today. I also tested and it is working in Incognito.

**Comment by atlasy97** [comment] 2023-11-11 09:18
Same issue here. Ublock is disabled on youtube. It was working fine for weeks previously. I noticed this issue yesterday, but I thought it was just some temporary bug, but it still keeps happening today.

**Comment by 0x48piraj** [comment] 2023-11-11 09:24
@atlasy97 works on incognito?

**Comment by atlasy97** [comment] 2023-11-11 09:44
@0x48piraj nope. I have enabled the extension to run in incognito, but it's till showing ads.  Here are some screenshots, if it's helpful:

![Picture1](https://github.com/0x48piraj/fadblock/assets/67227671/8421d38b-52e3-4943-bac6-e1b8556064d6)
[
![Picture2](https://github.com/0x48piraj/fadblock/assets/67227671/223f08ee-b227-4012-a03e-29534171f0ee)
![Picture3](https://github.com/0x48piraj/fadblock/assets/67227671/b8f142ca-e5f8-4ea4-9f78-155c03aec281)
![Picture4](https://github.com/0x48piraj/fadblock/assets/67227671/e9ccb903-62f3-4059-bee9-97f35c614f8d)
![Picture5](https://github.com/0x48piraj/fadblock/assets/67227671/36419068-10cb-44ba-aa1f-dc954989ea59)
](url)

**Comment by 0x48piraj** [comment] 2023-11-11 09:50
Gotcha. I am working on a new update.

**Comment by sergejsha** [comment] 2023-11-11 10:02
@0x48piraj checking for ".ytp-ad-preview-text-modern" in addition to ".ytp-ad-preview-text" worked for me.

```js
const skipLock = document.querySelector(".ytp-ad-preview-text")?.innerText ||
    document.querySelector(".ytp-ad-preview-text-modern")?.innerText; // <- condition fixing the issue
```

**Comment by usesben** [comment] 2023-11-11 10:03
I have the same issue, ads are not blocked and this started 11/11/2023. I have paid for this product to use. Not sure why it not works anymore. needs to get solved.

**Comment by usesben** [comment] 2023-11-11 10:04
I have the same issue, adds are not blocked and this started 11/11/2023. I have paid for this product to use. Not sure why it not works anymore. needs to get solved.

**Comment by 0x48piraj** [comment] 2023-11-11 10:07
@sergejsha, actually, the newer versions use Mutation Observer to be more performant and that version no longer works on many layers.

The new YT patch delays the `readyState`, and it's dabbling in `READYSTATE_HAVE_NOTHING` & `READYSTATE_HAVE_METADATA` a lot longer which is majorly causing the problem.

**Comment by 0x48piraj** [comment] 2023-11-11 10:08
Don't spam the same message @usesben, I am continually working on a fix. Do not worry.

**Comment by Victorlauni** [comment] 2023-11-11 10:16
I think youtube is doing ab testing, and fadblock is not really working on the new version of ads.
This is the new version 
![Screenshot 2023-11-11 051341](https://github.com/0x48piraj/fadblock/assets/20424855/5d74c474-73ee-44bf-886e-020cb2eeee92)
And this is the old version
![Screenshot 2023-11-11 051141](https://github.com/0x48piraj/fadblock/assets/20424855/5e7328c3-8db8-4e8e-bed1-de6873697aad)

I tested in using Firefox 119.0.1, and new version is showing in normal mode while old version is showing in incognito mode. The extension still working with the old version but not the new version.

**Comment by sergejsha** [comment] 2023-11-11 10:23
> @sergejsha, actually, the newer versions use Mutation Observer to be more performant and that version no longer works on many layers.
> 
> The new YT patch delays the `readyState`, and it's dabbling in `READYSTATE_HAVE_NOTHING` & `READYSTATE_HAVE_METADATA` a lot longer which is majorly causing the problem.

Not sure what version you refer to. I cloned an hour ago and used `master` branch. Is there a different version?

**Comment by 0x48piraj** [comment] 2023-11-11 10:29
@Victorlauni, yeah I figured, that's why I am setting up a server where FadBlock can fetch the new YouTube shenanigans.

After the next version goes live, I will be able to quickly release new patches.

@sergejsha, read the major announcement.

**Comment by 0x48piraj** [comment] 2023-11-11 12:40
I've rolled out the latest version on Firefox, and it'll be live soon (much quicker than Chrome). If you're using Firefox or just keen on testing out the new patch, give it a shot and let me know if everything's working as expected or not.

I will ping again after the update has gone live.

**Comment by lexscs** [comment] 2023-11-11 21:07
I have the same problem reported above, and to avoid any incompatibility, in Chrome I am only using this FadBlock

**Comment by usesben** [comment] 2023-11-12 14:27
Thank you looking forward to the update

Met vriendelijke groet,

Ben Wilmink

If you have any further questions, please do not hesitate to contact me, for your conveniences I have included more information and my contact details are provided under my signature as well the disclaimer.
Kind Regards,

Ben Wilmink

When you have eliminated all that is impossible, then whatever remains, however impossible, is the truth that is possible.

Disclaimer:
This email and its contents are provided for information exchange only.
The information contained in this electronic mail message or on the electronic media or printout or fax message is privileged and confidential and is intended only for the use of the addressee. This electronic message and its contents were sent by using Dutch mail server and or Dutch internet connections. The signed NDA applies to this electronic message. Confidentiality and legal privilege are not waived or lost by reason of mistaken delivery to you. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender by reply transmission and delete/destroy the message without copying or disclosing it. Nothing in this email shall bind the sender of the message in any contract or obligation. The choice of rights is the Dutch law and then in order the European Law and this choice of right prevails over any other choice of rights unless agreed and signed in written by parties involved.
The recipient should check this email and any attachments for the presence of viruses. The sender of the email and or electronic media accepts no liability for any damage caused by any virus or other malfunction caused or transmitted by this email, contents or electronic media.
No employee or agent is authorized to conclude any binding agreement on behalf of the company or of the sender himself with another party by email without specific written and signed confirmation.
***@***.******@***.***>

**Comment by Mex5150** [comment] 2023-11-12 17:27
> I've rolled out the latest version on Firefox, and it'll be live soon (much quicker than Chrome). 

Any ETA on the Chrome update, it's getting rather tedious having to keep skipping adverts by hand LOL

**Comment by Billkwando** [comment] 2023-11-12 19:42
> I've rolled out the latest version on Firefox, and it'll be live soon (much quicker than Chrome). If you're using Firefox or just keen on testing out the new patch, give it a shot and let me know if everything's working as expected or not.
> 
> I will ping again after the update has gone live.

It never showed a new Firefox update, even after the author said there was one, so I uninstalled and reinstalled. It still isn't blocking ads.

**Comment by 0x48piraj** [comment] 2023-11-14 05:00
The new version is out on Chrome!

**Comment by Meza85** [comment] 2023-11-14 05:45
looool fuck youtube hahahah it works again my man !!!!!!!!!!!!!!! letssss gooo (on chrome with 2.5) quick question tho i paid for 5.99 over operagx do i need to keep paying on chrome to use it as a premium (get updated) kinda thing not showing me some pop up to buy it i meant to ask. but yeh it works tho gg's

**Comment by 0x48piraj** [comment] 2023-11-14 06:41
Nope, you sure don't, just log in again with the email.

Also, use it on multiple devices, heck, share it with all your friends, I don't care! (just make sure they don't misuse your email or something, lol)

If you get any problem with payment or login and stuff, hit me up over email and we will hash it out!

The new version has a backend inbuilt, so... it's not going down, EVER! (hopefully)

**Comment by RayJohnson2** [comment] 2023-11-14 08:04
2.5 on Chrome seems to work for me! Thank you!!

**Comment by CrisWaller1** [comment] 2023-11-14 08:05
Working here as well- thank you!

**Comment by lexscs** [comment] 2023-11-14 11:47
At first, I saw that it was updated and it didn't work. I removed the extension, installed it again, opened Chrome again and voilá! Thanks man! Thank you from the bottom of my heart! When you go back to work, promise to make a donation, because you deserve it!

**Comment by 0x48piraj** [comment] 2023-11-14 12:22
Thank you for the kind words, I'm happy to help.

To be honest, because of the donations, I was happy to spin up a personal server for serving this project and for launching quicker updates. I am trying my best to make this extension as strong as possible so that our extension doesn't easily go down when YouTube releases weird patches.

Cheers!

**Comment by PaKheng96** [comment] 2023-11-14 14:04
![image](https://github.com/0x48piraj/fadblock/assets/150055208/adf68d40-463a-4468-aa4d-fe38753e3c31)
I think YouTube detects this extension as an adblock now. TT

Current version: 2.5

**Comment by 0x48piraj** [comment] 2023-11-14 15:08
@PaKheng96, go to `chrome://extensions` and post the results.

**Comment by Logical-Vanilla** [comment] 2023-11-14 20:59
@0x48piraj I was waiting to see if the next update would be able to fix the issue. YouTube was officially pissing me off. Not just forcing ads, but forcing the most brain-frying-mobile-game type crap that I've ever seen. Very glad to say next time I get the donate pop-up I'll support.

**Comment by 0x48piraj** [comment] 2023-11-25 18:08
2.6 working consistently, closing.

**Closed by 0x48piraj** 2023-11-25 18:08 UTC
