### ISSUE TITLE
Failing to stop ads on youtube

### ISSUE THREAD

**Issue by MrockzMan** [0x48piraj/fadblock#178] opened 2024-04-06 02:55 UTC
i've started getting ads again today, paid for a license today, did a clean install, still no luck
![image_2024-04-05_235415933](https://github.com/0x48piraj/fadblock/assets/166192641/e5341d57-a542-4e8a-9e85-36a7de6c7edf)

**Comment by pquodling** [comment] 2024-04-06 04:19
Yup, seeing the same.

**Comment by arrayoutofbounds** [comment] 2024-04-06 10:54
same

**Comment by scoobyclub** [comment] 2024-04-06 11:05
ditto. Youtube have found a way around it.

**Comment by brianlevin83** [comment] 2024-04-06 15:12
Seeing the same thing here as well, on Chrome Version 123.0.6312.106 (Official Build)

**Comment by scoobyclub** [comment] 2024-04-06 16:04
"Stands" ad-blocker seems to be working, possibly even more effectively than fadblock was. You can barely see the ads they run so fast.

**Comment by IvanLo0725** [comment] 2024-04-06 16:52
same.

**Comment by gps137** [comment] 2024-04-06 19:16
I believe the issue is YouTube changed the class name of the skip button to "ytp-skip-ad-button" instead of "ytp-ad-skip-button". If that's the sole issue, it should be an easy fix -- but I'm not confident enough in this being the only change to write up a pull request.

**Comment by 0x48piraj** [comment] 2024-04-09 23:23
Seems like it, the update was pushed geolocally so the old patch was working for many, seems like it's time to update.

**Comment by pquodling** [comment] 2024-04-11 22:32
So, there seems to be consensus on what caused this, and a code fix done - when will this be pushed out to a new install kit?  (or instructions to update)

**Comment by pquodling** [comment] 2024-04-17 09:33
Hello, is this thing turned on? Apparently a fix has been identified, and submitted for inclusion - but we have been waiting for a week to get this rolled out. It can't take that long to review/approve/build or whatever is required.

**Comment by 0x48piraj** [comment] 2024-04-18 00:32
The latest YouTube patch has not been deployed globally yet, so the previous version continues to function for the time being.

I've made updates to the backend, so if anyone encounters issues with the current version, they can simply update their installed FadBlock.

Here's how:

![image](https://github.com/0x48piraj/fadblock/assets/5800726/0ff837f1-7b1e-4da6-af6d-48b786e881e8)

**Comment by 0x48piraj** [comment] 2024-04-19 16:57
The issue was resolved this morning. Closing.

Reference thread for leaving remarks regarding this issue: https://github.com/0x48piraj/fadblock/issues/182

**Closed by 0x48piraj** 2024-04-19 16:57 UTC
